# Generated by Django 4.0.6 on 2022-07-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funcionarios_imagem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionarios',
            new_name='Funcionario',
        ),
    ]
