# Generated by Django 4.0.6 on 2022-08-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preco',
            name='icone',
            field=models.CharField(choices=[('lni-package', 'Caixa'), ('lni-drop', 'Gota'), ('lni-star', 'Estrela')], max_length=11, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='preco',
            name='preco',
            field=models.BigIntegerField(verbose_name='Preço'),
        ),
    ]
